name: USA
B: 0.0001
C: 0.0001
E: 0.0001
A: 0.0001
Ds: 0.0001
Di: 0.0001
Dr: 0.0001
gdp: 1000000
health_resource_stockpile: 0.1
sanitation_equipment_stockpile: 0
human_welfare_resource: 0.1
hapiness_index: 0.1
general_hospitals: 1000
procedure_resistance: 0.1
cleanliness_index: 0.1
base_death_rate: 0.001
vaccine_components:
  - name: A
    gdp_cost: 40765
    health_resource_cost: 0.1
    human_welfare_resource_cost: 0.1
    cost_gdp_perstep: 3435
    trickle: 0.1
  - name: B
    gdp_cost: 40
    health_resource_cost: 0.1
    human_welfare_resource_cost: 0.1
    cost_per_step: 3
    trickle: 0.1
  - name: C
    gdp_cost: 40
    health_resource_cost: 0.1
    human_welfare_resource_cost: 0.1
    cost_per_step: 3
    trickle: 0.1
  - name: D
    gdp_cost: 40
    health_resource_cost: 0.1
    human_welfare_resource_cost: 0.1
    cost_per_step: 3
    trickle: 0.1
  - name: E
    gdp_cost: 40
    health_resource_cost: 0.1
    human_welfare_resource_cost: 0.1
    cost_per_step: 3
    trickle: 0.1
loci:
  - name: California
    lat: 36.7783
    lon: 119.4179
    susceptible: 39538223
    infected: 100000
    recovered: 10
    area: 423970
    airports:
      - name: Los Angeles International Airport
        hub_tier: 1
      - name: San Francisco International Airport
        hub_tier: 2
    ports:
      - name: Port of Los Angeles
        hub_tier: 1
      - name: Port of Long Beach
        hub_tier: 1
    economic_zones:
      - name: Silicon Valley
        zone_tier: 1
      - name: Hollywood
        zone_tier: 2
      - name: Napa Valley
        zone_tier: 2
    tourist_zones:
      - name: Disneyland
        zone_tier: 1
      - name: Yosemite National Park
        zone_tier: 2
      - name: Golden Gate Bridge
        zone_tier: 2
  - name: New York
    lat: 40.7128
    lon: 74.006
    susceptible: 19453561
    infected: 100000
    recovered: 10
    area: 141300
    airports:
      - name: John F. Kennedy International Airport
        hub_tier: 1
      - name: LaGuardia Airport
        hub_tier: 2
    ports:
      - name: Port of New York and New Jersey
        hub_tier: 1
    economic_zones:
      - name: Wall Street
        zone_tier: 1
      - name: Broadway
        zone_tier: 2
      - name: Central Park
        zone_tier: 2
    tourist_zones:
      - name: Statue of Liberty
        zone_tier: 1
      - name: Times Square
        zone_tier: 2
      - name: Empire State Building
        zone_tier: 2
  - name: Texas
    lat: 31.9686
    lon: 99.9018
    susceptible: 29145505
    infected: 100000
    recovered: 10
    area: 695662
    airports:
      - name: Dallas/Fort Worth International Airport
        hub_tier: 1
      - name: George Bush Intercontinental Airport
        hub_tier: 2
    ports:
      - name: Port of Houston
        hub_tier: 1
      - name: Port of Corpus Christi
        hub_tier: 2
    economic_zones:
      - name: NASA
        zone_tier: 1
      - name: Alamo
        zone_tier: 2
      - name: South Padre Island
        zone_tier: 2
    tourist_zones:
      - name: The Alamo
        zone_tier: 1
      - name: NASA Space Center
        zone_tier: 2
      - name: South Padre Island Beach
        zone_tier: 2
  - name: Florida
    lat: 27.9944
    lon: 81.7603
    susceptible: 21538187
    infected: 100000
    recovered: 10
    area: 170312
    airports:
      - name: Miami International Airport
        hub_tier: 1
      - name: Orlando International Airport
        hub_tier: 2
    ports:
      - name: Port of Miami
        hub_tier: 1
      - name: Port Everglades
        hub_tier: 1
    economic_zones:
      - name: Disney World
        zone_tier: 1
      - name: Miami Beach
        zone_tier: 2
      - name: Everglades
        zone_tier: 2
    tourist_zones:
      - name: Disney World
        zone_tier: 1
      - name: Miami Beach
        zone_tier: 2
      - name: Everglades National Park
        zone_tier: 2
