---
name: USA
beta: 0.0001
gamma: 0.0001
epsilon: 0.0001
birth_ratio: 0.0001
death_ratio: 0.0001
loci:
- name: California
  lat: 36.7783
  lon: 119.4179
  population: 39538223
  airports:
  - name: Los Angeles International Airport
    tier: 1
  - name: San Francisco International Airport
    tier: 2
  ports:
  - name: Port of Los Angeles
    tier: 1
  - name: Port of Long Beach
    tier: 1