---
name: China
B: 0.0001
C: 0.0001
E: 0.0001
A: 0.0001
Ds: 0.0001
Di: 0.0001
Dr: 0.0001
gdp: 1000000
health_resource_stockpile: 0.1
sanitation_equipment_stockpile: 0
human_welfare_resource: 0.1
hapiness_index: 0.1
general_hospitals: 1000
procedure_resistance: 0.1
cleanliness_index: 0.1
base_death_rate: 0.001
vaccine_components:
  - name: A
    gdp_cost: 40765
    health_resource_cost: 0.1
    human_welfare_resource_cost: 0.1
    cost_gdp_perstep: 3435
    trickle: 0.1
  - name: B
    gdp_cost: 40
    health_resource_cost: 0.1
    human_welfare_resource_cost: 0.1
    cost_per_step: 3
    trickle: 0.1
  - name: C
    gdp_cost: 40
    health_resource_cost: 0.1
    human_welfare_resource_cost: 0.1
    cost_per_step: 3
    trickle: 0.1
  - name: D
    gdp_cost: 40
    health_resource_cost: 0.1
    human_welfare_resource_cost: 0.1
    cost_per_step: 3
    trickle: 0.1
  - name: E
    gdp_cost: 40
    health_resource_cost: 0.1
    human_welfare_resource_cost: 0.1
    cost_per_step: 3
    trickle: 0.1
loci:
  - name: Beijing
    lat: 39.9042
    lon: 116.4074
    susceptible: 21542000
    infected: 100000
    recovered: 10
    area: 16410
    airports:
      - name: Beijing Capital International Airport
        hub_tier: 1
      - name: Beijing Daxing International Airport
        hub_tier: 2
    ports:
      - name: Port of Tianjin
        hub_tier: 1
      - name: Port of Dalian
        hub_tier: 1
    economic_zones:
      - name: Zhongguancun
        zone_tier: 1
      - name: Wangfujing
        zone_tier: 2
      - name: Sanlitun
        zone_tier: 2
    tourist_zones:
      - name: Great Wall of China
        zone_tier: 1
      - name: Forbidden City
        zone_tier: 2
      - name: Summer Palace
        zone_tier: 2
  - name: Shanghai
    lat: 31.2304
    lon: 121.4737
    susceptible: 24237800
    infected: 100000
    recovered: 10
    area: 6340
    airports:
      - name: Shanghai Pudong International Airport
        hub_tier: 1
      - name: Shanghai Hongqiao International Airport
        hub_tier: 2
    ports:
      - name: Port of Shanghai
        hub_tier: 1
      - name: Port of Ningbo-Zhoushan
        hub_tier: 1
    economic_zones:
      - name: Lujiazui
        zone_tier: 1
      - name: Xintiandi
        zone_tier: 2
      - name: The Bund
        zone_tier: 2
    tourist_zones:
      - name: The Bund
        zone_tier: 1
      - name: Yu Garden
        zone_tier: 2
      - name: Oriental Pearl Tower
        zone_tier: 2
  - name: Guangdong
    lat: 23.379
    lon: 113.7633
    susceptible: 113460000
    infected: 100000
    recovered: 10
    area: 179800
    airports:
      - name: Guangzhou Baiyun International Airport
        hub_tier: 1
      - name: Shenzhen Bao'an International Airport
        hub_tier: 2
    ports:
      - name: Port of Guangzhou
        hub_tier: 1
      - name: Port of Shenzhen
        hub_tier: 1
    economic_zones:
      - name: Shenzhen SEZ
        zone_tier: 1
      - name: Guangzhou SEZ
        zone_tier: 2
      - name: Zhuhai SEZ
        zone_tier: 2
    tourist_zones:
      - name: Canton Tower
        zone_tier: 1
      - name: Chimelong Paradise
        zone_tier: 2
      - name: Window of the World
        zone_tier: 2
  - name: Zhejiang
    lat: 29.1549
    lon: 119.9573
    susceptible: 57370000
    infected: 100000
    recovered: 10
    area: 101800
    airports:
      - name: Hangzhou Xiaoshan International Airport
        hub_tier: 1
      - name: Ningbo Lishe International Airport
        hub_tier: 2
    ports:
      - name: Port of Ningbo-Zhoushan
        hub_tier: 1
      - name: Port of Wenzhou
        hub_tier: 1
    economic_zones:
      - name: Hangzhou SEZ
        zone_tier: 1
      - name: Ningbo SEZ
        zone_tier: 2
      - name: Wenzhou SEZ
        zone_tier: 2
    tourist_zones:
      - name: West Lake
        zone_tier: 1
      - name: Xixi National Wetland Park
        zone_tier: 2
      - name: Lingyin Temple
        zone_tier: 2
  - name: Sichuan
    lat: 30.6171
    lon: 102.7103
    susceptible: 83020000
    infected: 100000
    recovered: 10
    area: 485000
    airports:
      - name: Chengdu Shuangliu International Airport
        hub_tier: 1
      - name: Chengdu Tianfu International Airport
        hub_tier: 2
    ports:
      - name: Port of Luzhou
        hub_tier: 1
      - name: Port of Yibin
        hub_tier: 1
    economic_zones:
      - name: Chengdu SEZ
        zone_tier: 1
      - name: Mianyang SEZ
        zone_tier: 2
      - name: Leshan SEZ
        zone_tier: 2
    tourist_zones:
      - name: Mount Emei
        zone_tier: 1
      - name: Jiuzhaigou Valley
        zone_tier: 2
      - name: Leshan Giant Buddha
        zone_tier: 2
